---

# install java
- hosts: java
  sudo: yes

  roles:
    - java8-centos

# install redis
- hosts: redis
  sudo: yes

  roles:
    - redis

# install rdbms
- hosts: rdbms
  sudo: yes

  roles:
    - hsqldb

# install zookeeper
- hosts: zk
  sudo: yes

  roles:
    - {
        role: spring-xd,
        install_spring_xd: true,
        install_zk: true,
      }

# install and start spring-xd admins
- hosts: xd_admins
  sudo: yes

  roles:
    - {
        role: spring-xd,
        install_spring_xd: true,
        restart_admins: true
      }

# install and start spring-xd containers
- hosts: xd_containers
  sudo: yes

  roles:
    - {
        role: spring-xd,
        install_spring_xd: true,
        restart_containers: true
      }
