---

- name: install zookeper from spring-xd installation
  command: "./install-zookeeper"
  args:
    chdir: /opt/pivotal/spring-xd/zookeeper/bin/
    creates: zkServer.sh

- name: start zookeeper
  command: "./zkServer.sh restart"
  args:
    chdir: /opt/pivotal/spring-xd/zookeeper/bin/