---
- name: install wget
  yum: name=wget state=present

# Install Pivotal's GPG key for RPMs and their RPM repo
- command: "rpm --import http://packages.gopivotal.com/pub/rpm/rhel6/app-suite/RPM-GPG-KEY-PIVOTAL-APP-SUITE-EL6"
- command: "rpm -ivf  http://packages.gopivotal.com/pub/rpm/rhel6/app-suite/app-suite-repo-1.0-4.noarch.rpm"
  ignore_errors: yes

# Verify Pivotal's RPM repo is present so we can install Spring-XD
- yum: name=app-suite-repo state=present

# replace the lines that make you accept the EULA so it auto accepts
- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+less .*)"      replace='#\1'
- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+printf.*)"     replace='#\1'
- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+read reply.*)" replace='#\1'
- lineinfile: dest=/etc/pivotal/pivotal-eula-acceptance.sh line="      reply=yes" insertafter=".*read reply.*"

- name: run pivotal EULA to accept it automatically to get additional yum repos for spring-xd
  command: /etc/pivotal/pivotal-eula-acceptance.sh

- name: install spring-xd
  yum: name=spring-xd state=present

# Template spring-xd servers.yml file
- name: template spring-xd servers.yml
  template: src=servers.yml.j2 dest=/opt/pivotal/spring-xd/xd/config/servers.yml
  tags:
    - template

